### ISSUE TITLE
Sidebar show files

### ISSUE THREAD

**Issue by stoivo** [vlakarados/devastate#6]
I am wondering if it is possible to keep the file icon in the sidebar. I added two screenshots to show you what I mean.

![](https://cloud.githubusercontent.com/assets/3492040/15450715/9ec738fc-1fa3-11e6-8987-eb1bdf555150.png)

![](https://cloud.githubusercontent.com/assets/3492040/15450714/9ec69500-1fa3-11e6-9ac4-2eaa6806055b.png)
I created an issue on one package build on top of this one, shagabutdinov/sublime-devastate-mini#1

**Comment by vlakarados** [comment]
I have replied to you on the original issue in devastate-mini: https://github.com/shagabutdinov/sublime-devastate-mini/issues/1#issuecomment-222205766
TL;DR: I don't use ST anymore, it would be cool if someone made a PR with a second theme file that has icons enabled.
