### ISSUE TITLE
Would love to have this ported to iTerm2

### ISSUE THREAD

**Issue by iamajvillalobos** [vlakarados/devastate#8]
Any future plans? I really love your color scheme I know it's based from Dayle Reese but he also don't have themes for iTerm2.

**Comment by vlakarados** [comment]
I guess, no plans at all, you may post a PR with iTerm configuration file if you'll come up with it yourself, or make a fork, but this is pretty much neglected as I don't use ST anymore.

**Comment by iamajvillalobos** [comment]
No problem at all :), out of curiosity, what are you using now?

**Comment by vlakarados** [comment]
PHP Storm, didn't have time to port this theme, though, but maybe someday :)

**Comment by iamajvillalobos** [comment]
Yep! Thanks for replying, will close this now 👍
